### ISSUE TITLE
Wallet doesn't sync

### ISSUE THREAD

**Issue by ghost** [HTHcoin/HTH-Legacy-old-chain#16]
Hi,

As the title says, the wallet doesn't sync, at all. The peers list is always empty. Can we get a fix?

Thanks

**Comment by Altcoin-Cash** [comment]
While waiting for new wallets, use one of these lines in the debug window or after hth-cli 
addnode 178.62.236.242:35888 onetry
addnode 192.99.244.189:35888 onetry
addnode 202.39.49.57:35888 onetry
addnode 206.189.103.219:35888 onetry
addnode 209.250.241.214:35888 onetry
addnode 213.136.83.223:35888 onetry
addnode 31.25.241.224:35888 onetry
addnode 34.80.13.219:35888 onetry
addnode 45.32.193.66:35888 onetry
addnode 45.63.93.11:35888 onetry
addnode 45.76.185.27:35888 onetry

[More nodes](https://gpuhot.com/explorer/peers?id=2192)
